### ISSUE TITLE
Static IPs for Gateways

### ISSUE THREAD

**Issue by shaneutt** [Kong/blixt#96]
In order for [Gateway API](https://github.com/kubernetes-sigs/gateway-api) to release `v1.0.0` we need conformance tests for all things core and extended. One extended feature available for GA is the ability to statically assign addresses to a created `Gateway` resource rather than allowing those IPs to be dynamically provisioned:

https://github.com/kubernetes-sigs/gateway-api/issues/2035

The purpose of this task is to implement this functionality in Blixt, which supports both https://github.com/kubernetes-sigs/gateway-api/issues/2035 and https://github.com/Kong/blixt/issues/81, as well as https://github.com/kubernetes-sigs/gateway-api/issues/1794 and https://github.com/kubernetes-sigs/gateway-api/issues/1792.

After this is implemented, we need to plug the upstream conformance test suite into Blixt and start running Gateway API conformance tests as a part of our CI, at _least_ to the level of `Gateway` conformance for this iteration.

## TODO

- [ ] Implement static IP for `Gateways`
- [ ] https://github.com/Kong/blixt/issues/95
- [ ] https://github.com/kubernetes-sigs/gateway-api/issues/2035
- [ ] Enable conformance in Blixt for https://github.com/kubernetes-sigs/gateway-api/issues/2035

## Acceptance Criteria

- [ ] I can assign a static IP address from a known pool for my `Service` provider for any `Gateway` resource, and have traffic route properly using it
